# Generated by Django 3.0.3 on 2020-02-09 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='placeholder-200.png', upload_to='users/', verbose_name='Аватар')),
                ('gender', models.CharField(choices=[(None, 'Выберите пол'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default=None, max_length=7, verbose_name='Пол')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата рождения')),
                ('bio', models.TextField(max_length=1000, verbose_name='Личная информация')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватный')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
