# Generated by Django 3.0.3 on 2020-02-11 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pk'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-publication_date'], 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.RemoveField(
            model_name='story',
            name='url',
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='', editable=False, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Личная информация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Не указан', 'Не указан'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не указан', max_length=9, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='story',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 13, 43, 37, 649855, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Story', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-creation_date'],
            },
        ),
    ]
