# Generated by Django 3.0.3 on 2020-02-12 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 12, 37, 10, 865476, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
