# Generated by Django 3.0.3 on 2020-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(None, 'Выберите пол'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default=None, max_length=7, null=True, verbose_name='Пол'),
        ),
    ]
