# Generated by Django 3.0.3 on 2020-02-12 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200212_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
