# Generated by Django 3.0.3 on 2020-02-10 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='text',
        ),
        migrations.AddField(
            model_name='story',
            name='html_text',
            field=models.TextField(default='', editable=False, verbose_name='Обработанный текст'),
        ),
        migrations.AddField(
            model_name='story',
            name='markdown_text',
            field=models.TextField(default='', help_text='Тест в формате Markdown', verbose_name='Markdown-текст'),
        ),
        migrations.AlterField(
            model_name='story',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 10, 31, 12, 875563, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
