# Generated by Django 3.0.3 on 2020-02-10 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200210_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='markdown_text',
        ),
        migrations.AddField(
            model_name='story',
            name='as_md',
            field=models.BooleanField(default=True, verbose_name='Использовать Markdown'),
        ),
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(default='', help_text='Тест в формате Markdown', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='story',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 11, 57, 44, 1077, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
