# Generated by Django 3.0.3 on 2020-02-10 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200210_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 12, 3, 35, 65536, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
