# Generated by Django 3.0.3 on 2020-02-10 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200210_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='as_md',
            field=models.BooleanField(default=False, verbose_name='Использовать Markdown'),
        ),
        migrations.AlterField(
            model_name='story',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 12, 4, 33, 822491, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
